name: build android apps
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "docs/**"
      - "README.md"
      - ".github/ISSUE_TEMPLATE/**"
    branches:
      - main
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: update version
        run: |
          sed -i "s|versionCode .*|versionCode $(date +%Y%m%d)|g" app/build.gradle
          sed -i "s|versionName .*|versionName \"1.14-$(git rev-parse --short HEAD)\"|g" app/build.gradle
 
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew --no-daemon --no-configuration-cache -q app:assembleRelease

      - name: checking release version
        id: version
        run: |
          echo "RELEASE_VERSION=$(cat app/build.gradle  | grep -o "versionName \"[0-9.]*-[a-z,0-9]*\"" | grep -o "[0-9.]*-[a-z,0-9]*")" >> $GITHUB_OUTPUT

      - name: rename apks
        run: |
          APK="Box4Magisk-Manager_v${{ steps.version.outputs.RELEASE_VERSION }}.apk"
          mv -f ./app/build/outputs/apk/release/*.apk ./app/build/outputs/apk/release/$APK

      - name: Sign apk
        uses: d2184/android-sign@main
        with:
          releaseDirectory: ./app/build/outputs/apk/release
          output: ./app/build/outputs/apk/release/signed
          alias: ${{ secrets.KEY_ALIAS }}
          signingKeyBase64: ${{ secrets.KEYSTORE_CONTENT }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Delete current Prerelease-alpha assets
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: Prerelease-Alpha
          assets: "*.apk"
          fail-if-no-release: false
          fail-if-no-assets: false

      - name: Public
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: Prerelease-Alpha
          release_name: Prerelease-Alpha
          file: "./app/build/outputs/apk/release/signed/*.apk"
          prerelease: true
          overwrite: true
          file_glob: true
